// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sandbattery_backend.Data;

#nullable disable

namespace sandbattery_backend.Migrations
{
    [DbContext(typeof(SandbatteryDbContext))]
    [Migration("20260428190020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("sandbattery_backend.Data.Entities.ActuatorStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Actuator")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("actuator");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_changed");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ProductKey", "Actuator")
                        .IsUnique();

                    b.ToTable("actuator_status");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.AlertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("acknowledged");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_key");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("alert");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("ProductKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_key");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_name");

                    b.HasKey("ProductKey");

                    b.ToTable("device");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.ElectricityPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("area");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("currency");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("date");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Area")
                        .IsUnique();

                    b.ToTable("electricity_price");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("event");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.HeartbeatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_key");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UptimeSeconds")
                        .HasColumnType("int")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("Id");

                    b.ToTable("heartbeat");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.PriceEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectricityPriceId")
                        .HasColumnType("int")
                        .HasColumnName("electricity_price_id");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hour");

                    b.Property<float>("PriceDkkKwh")
                        .HasColumnType("float")
                        .HasColumnName("price_dkk_kwh");

                    b.HasKey("Id");

                    b.HasIndex("ElectricityPriceId");

                    b.ToTable("price_entry");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.SensorMeasurementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("float")
                        .HasColumnName("energy_kwh");

                    b.Property<float>("FlowRate")
                        .HasColumnType("float")
                        .HasColumnName("flow_rate");

                    b.Property<float>("PowerW")
                        .HasColumnType("float")
                        .HasColumnName("power_w");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_key");

                    b.Property<float>("SandTemp")
                        .HasColumnType("float")
                        .HasColumnName("sand_temp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<float>("WaterTempIn")
                        .HasColumnType("float")
                        .HasColumnName("water_temp_in");

                    b.Property<float>("WaterTempOut")
                        .HasColumnType("float")
                        .HasColumnName("water_temp_out");

                    b.HasKey("Id");

                    b.ToTable("sensor_measurement");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoHeatingEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_heating_enabled");

                    b.Property<bool>("AutoPumpEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_pump_enabled");

                    b.Property<float>("MaxSandTemp")
                        .HasColumnType("float")
                        .HasColumnName("max_sand_temp");

                    b.Property<float>("MinPumpTemp")
                        .HasColumnType("float")
                        .HasColumnName("min_pump_temp");

                    b.Property<float>("PriceLimitDkk")
                        .HasColumnType("float")
                        .HasColumnName("price_limit_dkk");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_key");

                    b.Property<int>("PumpIntervalSeconds")
                        .HasColumnType("int")
                        .HasColumnName("pump_interval_seconds");

                    b.HasKey("Id");

                    b.HasIndex("ProductKey")
                        .IsUnique();

                    b.ToTable("settings");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.PriceEntryEntity", b =>
                {
                    b.HasOne("sandbattery_backend.Data.Entities.ElectricityPriceEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("ElectricityPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.ElectricityPriceEntity", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
