// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sandbattery_backend.Data;

#nullable disable

namespace sandbattery_backend.Migrations
{
    [DbContext(typeof(SandbatteryDbContext))]
    partial class SandbatteryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("sandbattery_backend.Data.Entities.ActuatorStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Actuator")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("actuator");

                    b.Property<int>("ActuatorIndex")
                        .HasColumnType("int")
                        .HasColumnName("actuator_index");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_changed");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Actuator", "ActuatorIndex")
                        .IsUnique();

                    b.ToTable("actuator_status");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.AlertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("acknowledged");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("alert");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_name");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_key");

                    b.HasKey("Id");

                    b.HasIndex("ProductKey")
                        .IsUnique();

                    b.ToTable("device");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.ElectricityPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("area");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("currency");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("date");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Area")
                        .IsUnique();

                    b.ToTable("electricity_price");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("event");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.FlowRateSensorReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int")
                        .HasColumnName("measurement_id");

                    b.Property<int>("SensorIndex")
                        .HasColumnType("int")
                        .HasColumnName("sensor_index");

                    b.Property<float>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("flow_rate_sensor_reading");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.HeartbeatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UptimeSeconds")
                        .HasColumnType("int")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("Id");

                    b.ToTable("heartbeat");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.PriceEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectricityPriceId")
                        .HasColumnType("int")
                        .HasColumnName("electricity_price_id");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hour");

                    b.Property<float>("PriceDkkKwh")
                        .HasColumnType("float")
                        .HasColumnName("price_dkk_kwh");

                    b.HasKey("Id");

                    b.HasIndex("ElectricityPriceId");

                    b.ToTable("price_entry");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.SensorMeasurementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("float")
                        .HasColumnName("energy_kwh");

                    b.Property<float>("PowerW")
                        .HasColumnType("float")
                        .HasColumnName("power_w");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("sensor_measurement");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoHeatingEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_heating_enabled");

                    b.Property<bool>("AutoPumpEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_pump_enabled");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<float>("MaxSandTemp")
                        .HasColumnType("float")
                        .HasColumnName("max_sand_temp");

                    b.Property<float>("MinPumpTemp")
                        .HasColumnType("float")
                        .HasColumnName("min_pump_temp");

                    b.Property<float>("PriceLimitDkk")
                        .HasColumnType("float")
                        .HasColumnName("price_limit_dkk");

                    b.Property<int>("PumpIntervalSeconds")
                        .HasColumnType("int")
                        .HasColumnName("pump_interval_seconds");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("settings");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.TemperatureSensorReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("label");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int")
                        .HasColumnName("measurement_id");

                    b.Property<int>("SensorIndex")
                        .HasColumnType("int")
                        .HasColumnName("sensor_index");

                    b.Property<float>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("temperature_sensor_reading");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.FlowRateSensorReadingEntity", b =>
                {
                    b.HasOne("sandbattery_backend.Data.Entities.SensorMeasurementEntity", null)
                        .WithMany("FlowRateReadings")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.PriceEntryEntity", b =>
                {
                    b.HasOne("sandbattery_backend.Data.Entities.ElectricityPriceEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("ElectricityPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.TemperatureSensorReadingEntity", b =>
                {
                    b.HasOne("sandbattery_backend.Data.Entities.SensorMeasurementEntity", null)
                        .WithMany("TemperatureReadings")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.ElectricityPriceEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("sandbattery_backend.Data.Entities.SensorMeasurementEntity", b =>
                {
                    b.Navigation("FlowRateReadings");

                    b.Navigation("TemperatureReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
